services:
  - type: web
    name: antigraviity-crm
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.x # or 20.x
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://antigraviity-crm-cxmf.onrender.com # Use your actual Render URL here
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_COMMUNICATION_URL
        value: https://antigraviity-crm-cxmf.onrender.com
      - key: PORT
        value: 10000
