var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/admin/monitoring/screenshots/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b4873e14._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_732e5002._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2d7a599d._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__270c46a8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_f3782ad7._.js")
R.c("server/chunks/ssr/ce889_server_app_(dashboard)_admin_monitoring_screenshots_page_actions_7f512db6.js")
R.m(77639)
module.exports=R.m(77639).exports
