var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/recruitment/route.js")
R.c("server/chunks/[root-of-the-server]__df7c91db._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_94fc1a82.js")
R.c("server/chunks/[root-of-the-server]__870d157e._.js")
R.c("server/chunks/node_modules_moment_20d01de1._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_recruitment_route_actions_ede0a0e4.js")
R.m(34711)
module.exports=R.m(34711).exports
