var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/attendance/route.js")
R.c("server/chunks/[root-of-the-server]__becf0063._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_999db1bd.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/[root-of-the-server]__870d157e._.js")
R.c("server/chunks/node_modules_moment_20d01de1._.js")
R.c("server/chunks/_next-internal_server_app_api_attendance_route_actions_e944b69d.js")
R.m(54976)
module.exports=R.m(54976).exports
