// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/attendance" | "/admin/employees/anniversaries" | "/admin/employees/birthdays" | "/admin/employees/probation" | "/admin/monitoring/alerts" | "/admin/monitoring/audit-logs" | "/admin/monitoring/employees" | "/admin/monitoring/live" | "/admin/monitoring/live-wall" | "/admin/monitoring/overview" | "/admin/monitoring/reports" | "/admin/monitoring/screenshots" | "/admin/monitoring/settings" | "/announcements" | "/attendance" | "/careers" | "/careers/[id]" | "/clients" | "/communication" | "/communication/chat" | "/communication/rooms" | "/communication/video" | "/daily-reports" | "/daily-tasks" | "/dashboard" | "/documents" | "/employees" | "/employees/[id]" | "/employees/[id]/about" | "/holidays" | "/leads" | "/leave-approvals" | "/leave-tracker" | "/login" | "/manage-teams" | "/meetings" | "/monitoring/audit" | "/monitoring/my-activity" | "/monitoring/productivity" | "/monitoring/settings" | "/monitoring/team-activity" | "/my-team" | "/onboarding" | "/payroll" | "/performance" | "/projects" | "/recruitment" | "/reports" | "/settings" | "/support" | "/tasks" | "/team-attendance" | "/team-overview" | "/test-session"
type AppRouteHandlerRoutes = "/api/announcements" | "/api/announcements/[id]/seen" | "/api/applicants" | "/api/attendance" | "/api/attendance/action" | "/api/auth/[...nextauth]" | "/api/communication/rooms" | "/api/daily-checklist" | "/api/daily-reports" | "/api/daily-reports/[id]" | "/api/daily-tasks" | "/api/dashboard/stats" | "/api/dev-sw.js" | "/api/documents" | "/api/documents/[id]" | "/api/employees/[id]" | "/api/employees/[id]/about" | "/api/employees/[id]/offer-letter" | "/api/employees/[id]/stats" | "/api/holidays" | "/api/jobs" | "/api/jobs/public" | "/api/jobs/public/[id]" | "/api/leave" | "/api/manpower" | "/api/meetings" | "/api/meetings/[id]" | "/api/monitoring/activity" | "/api/monitoring/consent" | "/api/monitoring/screenshots" | "/api/monitoring/session" | "/api/monitoring/settings" | "/api/monitoring/stats" | "/api/monitoring/v2/audit" | "/api/onboarding/approve" | "/api/onboarding/stats" | "/api/payroll" | "/api/performance" | "/api/projects" | "/api/recruitment" | "/api/recruitment/stats" | "/api/reports" | "/api/search" | "/api/support" | "/api/support/[id]" | "/api/tasks" | "/api/tasks/[id]" | "/api/teams/assign" | "/api/users" | "/api/users/[id]" | "/api/users/[id]/documents" | "/api/users/anniversaries" | "/api/users/birthdays" | "/api/users/probation" | "/dev-sw.js"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/attendance": {}
  "/admin/employees/anniversaries": {}
  "/admin/employees/birthdays": {}
  "/admin/employees/probation": {}
  "/admin/monitoring/alerts": {}
  "/admin/monitoring/audit-logs": {}
  "/admin/monitoring/employees": {}
  "/admin/monitoring/live": {}
  "/admin/monitoring/live-wall": {}
  "/admin/monitoring/overview": {}
  "/admin/monitoring/reports": {}
  "/admin/monitoring/screenshots": {}
  "/admin/monitoring/settings": {}
  "/announcements": {}
  "/api/announcements": {}
  "/api/announcements/[id]/seen": { "id": string; }
  "/api/applicants": {}
  "/api/attendance": {}
  "/api/attendance/action": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/communication/rooms": {}
  "/api/daily-checklist": {}
  "/api/daily-reports": {}
  "/api/daily-reports/[id]": { "id": string; }
  "/api/daily-tasks": {}
  "/api/dashboard/stats": {}
  "/api/dev-sw.js": {}
  "/api/documents": {}
  "/api/documents/[id]": { "id": string; }
  "/api/employees/[id]": { "id": string; }
  "/api/employees/[id]/about": { "id": string; }
  "/api/employees/[id]/offer-letter": { "id": string; }
  "/api/employees/[id]/stats": { "id": string; }
  "/api/holidays": {}
  "/api/jobs": {}
  "/api/jobs/public": {}
  "/api/jobs/public/[id]": { "id": string; }
  "/api/leave": {}
  "/api/manpower": {}
  "/api/meetings": {}
  "/api/meetings/[id]": { "id": string; }
  "/api/monitoring/activity": {}
  "/api/monitoring/consent": {}
  "/api/monitoring/screenshots": {}
  "/api/monitoring/session": {}
  "/api/monitoring/settings": {}
  "/api/monitoring/stats": {}
  "/api/monitoring/v2/audit": {}
  "/api/onboarding/approve": {}
  "/api/onboarding/stats": {}
  "/api/payroll": {}
  "/api/performance": {}
  "/api/projects": {}
  "/api/recruitment": {}
  "/api/recruitment/stats": {}
  "/api/reports": {}
  "/api/search": {}
  "/api/support": {}
  "/api/support/[id]": { "id": string; }
  "/api/tasks": {}
  "/api/tasks/[id]": { "id": string; }
  "/api/teams/assign": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/users/[id]/documents": { "id": string; }
  "/api/users/anniversaries": {}
  "/api/users/birthdays": {}
  "/api/users/probation": {}
  "/attendance": {}
  "/careers": {}
  "/careers/[id]": { "id": string; }
  "/clients": {}
  "/communication": {}
  "/communication/chat": {}
  "/communication/rooms": {}
  "/communication/video": {}
  "/daily-reports": {}
  "/daily-tasks": {}
  "/dashboard": {}
  "/dev-sw.js": {}
  "/documents": {}
  "/employees": {}
  "/employees/[id]": { "id": string; }
  "/employees/[id]/about": { "id": string; }
  "/holidays": {}
  "/leads": {}
  "/leave-approvals": {}
  "/leave-tracker": {}
  "/login": {}
  "/manage-teams": {}
  "/meetings": {}
  "/monitoring/audit": {}
  "/monitoring/my-activity": {}
  "/monitoring/productivity": {}
  "/monitoring/settings": {}
  "/monitoring/team-activity": {}
  "/my-team": {}
  "/onboarding": {}
  "/payroll": {}
  "/performance": {}
  "/projects": {}
  "/recruitment": {}
  "/reports": {}
  "/settings": {}
  "/support": {}
  "/tasks": {}
  "/team-attendance": {}
  "/team-overview": {}
  "/test-session": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
