// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/employees/anniversaries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees/anniversaries">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/employees/anniversaries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/employees/birthdays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees/birthdays">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/employees/birthdays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/employees/probation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees/probation">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/employees/probation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/employees">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/live-wall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/live-wall">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/live-wall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/live">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/screenshots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/screenshots">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/screenshots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/admin/monitoring/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitoring/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/admin/monitoring/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/communication/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communication/chat">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/communication/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communication">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/communication/rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communication/rooms">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/communication/rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/communication/video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communication/video">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/communication/video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/daily-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/daily-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/daily-tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-tasks">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/daily-tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/employees/[id]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]/about">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/employees/[id]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/holidays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/holidays">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/holidays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leave-approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave-approvals">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leave-approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leave-tracker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave-tracker">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leave-tracker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/manage-teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manage-teams">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/manage-teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/monitoring/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring/audit">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/monitoring/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/monitoring/my-activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring/my-activity">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/monitoring/my-activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/monitoring/productivity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring/productivity">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/monitoring/productivity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/monitoring/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/monitoring/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/monitoring/team-activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring/team-activity">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/monitoring/team-activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/my-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-team">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/my-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/recruitment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/recruitment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/team-attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team-attendance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/team-attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/team-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team-overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/team-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/test-session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-session">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/test-session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/careers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/[id]/seen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements/[id]/seen">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/[id]/seen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/applicants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/applicants">> = Specific
  const handler = {} as typeof import("../../src/app/api/applicants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/action">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communication/rooms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communication/rooms">> = Specific
  const handler = {} as typeof import("../../src/app/api/communication/rooms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily-checklist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-checklist">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily-checklist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily-reports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-reports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily-reports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-sw.js/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-sw.js">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-sw.js/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/about/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/about">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/about/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/offer-letter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/offer-letter">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/offer-letter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/holidays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/holidays">> = Specific
  const handler = {} as typeof import("../../src/app/api/holidays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/public/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/public/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/public/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/public">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/manpower/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manpower">> = Specific
  const handler = {} as typeof import("../../src/app/api/manpower/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meetings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/meetings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meetings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/api/meetings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/consent">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/screenshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/screenshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/screenshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/v2/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/v2/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/v2/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/support/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/support/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support">> = Specific
  const handler = {} as typeof import("../../src/app/api/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/teams/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/teams/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/anniversaries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/anniversaries">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/anniversaries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/birthdays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/birthdays">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/birthdays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/probation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/probation">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/probation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-sw.js/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dev-sw.js">> = Specific
  const handler = {} as typeof import("../../src/app/dev-sw.js/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
