var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/payroll/route.js")
R.c("server/chunks/[root-of-the-server]__df7c91db._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_b10b50f8.js")
R.c("server/chunks/[root-of-the-server]__870d157e._.js")
R.c("server/chunks/node_modules_moment_20d01de1._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_payroll_route_actions_abe57a5f.js")
R.m(41902)
module.exports=R.m(41902).exports
