var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/users/route.js")
R.c("server/chunks/[root-of-the-server]__7a6ed4f2._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_214f6c26.js")
R.c("server/chunks/node_modules_moment_20d01de1._.js")
R.c("server/chunks/[root-of-the-server]__870d157e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/_next-internal_server_app_api_users_route_actions_4b9121e3.js")
R.m(75468)
module.exports=R.m(75468).exports
